---
Domain: #<DEFINE_ME>
replicas: 1
resources:
  limits:
    cpu: 200m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 512Mi

formsflow:
  configmap: forms-flow-ai # name of formsflow.ai configmap
  secret: forms-flow-ai #name of formsflow.ai secret
  auth: forms-flow-ai-auth
ingress:
  ingressClassName: ""
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE, PATCH"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
  enabled: true # create an ingress for this component 
  hostname: "forms-flow-web-{{.Release.Namespace}}.{{tpl .Values.Domain .}}"
  port: 5006
  tls: true
  selfSigned: false
  extraTls:
   - {}  
image:
  registry: docker.io
  repository: formsflow/forms-flow-documents-api
  tag: v7.0.0-alpha #The image tag to pull from
hpa:
  enabled: false 
  CpuAverageUtilization: 80
  maxReplicas: 3
elastic_search:
  enabled: false