apiVersion: external-secrets.io/v1beta1
kind: SecretStore # You could also choose ClusterSecretStore 
metadata:
  name: forms-flow-secret-store-vault
  # namespace: vault
spec:
  provider:
    vault:
      server: "http://my.vault.server:8200"  # vault address
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2".
      version: "v2"
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "vault-token"
          key: "token" # vault token
