apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app: "{{ .Chart.Name }}"
  name: "{{ .Chart.Name }}"
spec:
  refreshInterval: "15s" # The secrets will be refreshed every 15 seconds
  secretStoreRef:
    name: secret-store-vault # Reference to the secret store we have created above
    kind: SecretStore 
  target:
    name: forms-flow-ai # K8S secret name
  dataFrom:
  - extract:
      key: kv/forms-flow.ai/secrets/forms-flow-ai # To get all the secrets

  # data:
  #   - secretKey: FORMIO_ROOT_EMAIL
  #     remoteRef:
  #       key: kv/forms-flow.ai/secrets/forms-flow-ai
  #       property: FORMIO_ROOT_EMAIL

---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Chart.Name }}-auth
  name: {{ .Chart.Name }}-auth
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ index .Values "forms-flow-auth" "imagesecret" }}
