---
apiVersion: v1
data:

kind: ConfigMap
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
---
apiVersion: v1
data:
  mail-config.properties: |
    # send mails via SMTP
    mail.transport.protocol={{.Values.mail.protocol}}
    mail.smtp.auth={{.Values.mail.smtp.auth}}
    mail.smtp.host={{.Values.mail.smtp.server}}
    mail.smtp.port={{.Values.mail.smtp.port}}
    mail.smtp.ssl.enable={{.Values.mail.smtp.ssl.enable}}
    mail.smtp.socketFactory.port={{.Values.mail.smtp.socketFactory.port}}
    mail.smtp.socketFactory.class={{.Values.mail.smtp.socketFactory.class}}
    # poll mails via IMAPS
    #mail.store.protocol={{.Values.mail.store.protocol}}
    # mail.imaps.host={{.Values.mail.imaps.host}}
    mail.imaps.port={{.Values.mail.imaps.port}} 
    mail.imaps.timeout={{.Values.mail.imaps.timeout}}
    # additional config
    #mail.poll.folder={{.Values.mail.folder}}
    mail.sender={{.Values.mail.from}}
    mail.sender.alias={{.Values.mail.alias}}
    mail.attachment.download={{.Values.mail.attachment.download}}
    mail.attachment.path={{.Values.mail.attachment.path}}
    # credentials
    mail.user={{.Values.mail.user}}
    mail.password={{.Values.mail.password}}

kind: ConfigMap
metadata:
  labels:
    app: {{ .Chart.Name }}-mail-config
  name: {{ .Chart.Name }}-mail-config
---
{{- if .Values.elastic_search.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-fb-config
data:
  "filebeat.yml": |-
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /logs/*
    output.elasticsearch:
      hosts: "${ELASTIC_SERVER}"
      index: "forms-flow-bpm-%{+yyyy.MM.dd}"
    setup.template.name: "forms-flow-bpm"
    setup.template.pattern: "forms-flow-bpm-*"
    setup.template.overwrite: true
    setup.template.enabled: false
    setup.template.settings:
      index.number_of_shards: 1
    setup.ilm.enabled: false 
{{- end }}   