apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app: "{{ .Chart.Name }}"
  name: "{{ .Chart.Name }}"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: secret-store-vault
    kind: SecretStore 
  target:
    name: forms-flow-bpm
  dataFrom:
  - extract:
      key: kv/forms-flow.ai/secrets/forms-flow-bpm